# This Deployment rolls the Joomla-Webfrontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla-eiche
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: artifactory.home.local/eiche/joomla:4.2.8
        ports:
        - containerPort: 80